name: Example Workflow using Environment Variables
on:
  workflow_dispatch:

env:
 DAY_OF_WEEK: Monday
jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    
    steps:
      - name: Environment Declaration
        run: echo "$Greeting $First_Name . Today is $DAY_OF_WEEK "
        env:
         First_Name: Daniel 
