name: Example Workflow using Environment Variables
on:
  push:
    branches: ["main"]


env:
 DAY_OF_WEEK: Monday
jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    
    steps:
      - name: Environment Declaration
        run: echo "$Greeting $FirstName . Today is $DAY_OF_WEEK "
        env:
         First_Name: Daniel 
